Repository GlueOps/terraform-module-cloud-aws-cloud-developer-environments, pull requests merged in 2024-10, with the labels that each got.

#1 feat: initial migration
  .github/README.md
  .github/workflows/docs.yaml
  README.md
  cde-full-setup/README.md
  cde-full-setup/launch-template.tf
  cde-full-setup/network.tf
  cde-iam-setup/README.md
  cde-iam-setup/ec2-connect.tf
  cde-iam-setup/iam-policy-password-mgmt.tf
  cde-iam-setup/main.tf
  cde-iam-setup/variables.tf
Labels: Review effort [1-5]: 4

#3 feat: add packer user and improve user creation logic
  cde-iam-setup/README.md
  cde-iam-setup/main.tf
  cde-iam-setup/packer.tf
Labels: Review effort [1-5]: 3

#5 major: delete packer user since we now have a central account for it
  cde-iam-setup/README.md
  cde-iam-setup/packer.tf
Labels: Review effort [1-5]: 1

#6 feat: only keep 1 sg
  cde-full-setup/README.md
  cde-full-setup/launch-template.tf
  cde-full-setup/network.tf
Labels: enhancement, Review effort [1-5]: 2

#7 feat: adding iam-user-slackbot.tf
  cde-iam-setup/README.md
  cde-iam-setup/iam-user-slackbot.tf
Labels: enhancement, Review effort [1-5]: 2

#14 [skip actions] synced file(s) with internal-GlueOps/github-shared-files-sync
  .github/release.yml
Labels: Review effort [1-5]: 1, sync, configuration changes
